#!/bin/sh
# postinst script for subtitle-buddy

echo "Starting postinst script" >> /tmp/postinst.log

# Create symlink to make subtitle-buddy executable globally accessible
ln -sf /opt/subtitle-buddy/bin/subtitle-buddy /usr/local/bin/subtitle-buddy

if [ $? -eq 0 ]; then
    echo "Symlink created successfully."
else
    echo "Failed to create symlink."
fi

echo "Trying to create symlink" >> /tmp/postinst.log
echo "Symlink creation status: $?" >> /tmp/postinst.log

exit $?
